Add statsite support
openprocurement/openprocurement.documentservice.buildout pull request #2
Opened 2017-05-03 11:16 UTC by VDigitall

2017-05-03 14:05 UTC, kroman0 commented on templates/service.ini
> +handlers = console{% if 'journal' in options %},journal{% end %}${',statsite' if 'statsite' in options else ''}
console не буде дублюватись в root

2017-05-03 14:05 UTC, kroman0 commented on development.cfg
> +dockey = ''
Того не треба

2017-05-04 10:06 UTC, VDigitall commented on development.cfg
> +dockey = ''
без цього не будувався білдаут

2017-05-04 11:12 UTC, VDigitall commented
Виправив

2017-05-15 10:07 UTC, kroman0 requested changes

2017-05-15 10:07 UTC, kroman0 commented on templates/service.ini
> +handlers = console{% if 'journal' in options %},journal{% end %}${',statsite' if 'statsite' in options else ''}
console тут зайве

2017-05-15 10:07 UTC, kroman0 commented on buildout.cfg.example
> -extends = development.cfg
Цього не треба міняти

2017-05-15 10:07 UTC, kroman0 commented on development.cfg
> +dockey = ''
Тоді краще додати в buildout.cfg.example

2017-05-15 10:07 UTC, kroman0 commented on statsite.cfg
> +[ds_handler.yaml]
тут тільки ds тому можна зробити просто handler.yaml або statsdhandler.yaml

2017-05-15 12:02 UTC, VDigitall commented
Виправив

2017-05-15 12:59 UTC, kroman0 commented on buildout.cfg.example
> -extends = development.cfg
ping

2017-05-15 13:00 UTC, kroman0 commented on templates/service.ini
> +handlers = {% if 'journal' in options %}journal{% end %}{% if 'statsd' in options and 'journal' in options %},statsd{% end %}{% if 'statsd' in options and 'journal' not in options %}statsd{% end %}
трохи за складно

2017-05-15 13:00 UTC, kroman0 reviewed
А чого versions.cfg видалив?

2017-05-15 13:04 UTC, VDigitall commented
Поправив.

2017-05-15 13:07 UTC, VDigitall commented
Поправив

2017-05-15 14:40 UTC, kroman0 approved these changes

2017-05-15 14:40 UTC, merged